using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace eVidaGeneralLib.VO {
	[Serializable]
	public class CategoriaModuloVO {
		public int Id { get; set; }
		public string Nome { get; set; }
	}

	[Serializable]
	public class ModuloVO {
		public int Id { get; set; }
		public string Nome { get; set; }
		public Modulo Value { get; set; }
		public int IdCategoria { get; set; }
	}

	public enum Modulo {
		LOGIN = -1,
		INICIAL = -2,
		ADMINISTRACAO_PERFIL_MODULO = 101,
		ADMINISTRACAO_USUARIO = 102,
		ADMINISTRACAO_EMP_RECIPROCIDADE = 103,
		ADMINISTRACAO_PLANTAO_SOCIAL = 104,
		ADMINISTRACAO_CONSELHO = 105,
		ADMINISTRACAO_TEMPLATE_EMAIL = 106,
		ADMINISTRACAO_MOTIVO_PENDENCIA = 107,
		ADMINISTRACAO_CANAL_GESTANTE = 108,
		ADMINISTRACAO_SETOR_USUARIO = 109,
		ADMINISTRACAO_USUARIO_SCL = 110,
		ADMINISTRACAO_VIAGEM_PARAMETRO = 120,
        ADMINISTRACAO_ENDERECO_COBRANCA = 130,

		GESTAO_SEG_VIA = 301,
		NEGATIVA = 302,
		APROVAR_NEGATIVA = 303,
        RECEBER_EMAIL_NEGATIVA = 304,

		EXCLUSAO = 305,
		UNIVERSITARIO = 306,
		ATESTADO_COMPARECIMENTO = 307,
		AUTORIZACAO = 308,
		GERIR_AUTORIZACAO_MEDICA = 309,
		GERIR_AUTORIZACAO_ODONTO = 310,
		AUTORIZACAO_PROVISORIA = 311,
		APROVAR_AUTORIZACAO_PROVISORIA = 312,
		INDISPONIBILIDADE_REDE = 313,
		INDISPONIBILIDADE_REDE_CREDENCIAMENTO = 314,
		INDISPONIBILIDADE_REDE_DIRETORIA = 315,
		INDISPONIBILIDADE_REDE_FATURAMENTO = 316,
		INDISPONIBILIDADE_REDE_FINANCEIRO = 317,
		INDISPONIBILIDADE_REDE_AUTORIZACAO = 318,
		INDISPONIBILIDADE_REDE_SUPER = 319,
		INDISPONIBILIDADE_REDE_REGIONAL = 320,
        INDISPONIBILIDADE_REDE_CADASTRO = 321,
        INDISPONIBILIDADE_REDE_BENEFICIARIO = 322,

        INDISPONIBILIDADE_REDE_SEFAT_CM = 380,
        INDISPONIBILIDADE_REDE_SEFAT_RB = 381,
        INDISPONIBILIDADE_REDE_PAT_ARARAQUARA = 382,
        INDISPONIBILIDADE_REDE_PAT_BELEM = 383,
        INDISPONIBILIDADE_REDE_PAT_BOAVISTA = 384,
        INDISPONIBILIDADE_REDE_PAT_CUIABA = 385,
        INDISPONIBILIDADE_REDE_PAT_IMPERATRIZ = 386,
        INDISPONIBILIDADE_REDE_PAT_MACAPA = 387,
        INDISPONIBILIDADE_REDE_PAT_MANAUS = 388,
        INDISPONIBILIDADE_REDE_PAT_MARABA = 389,
        INDISPONIBILIDADE_REDE_PAT_PALMAS = 390,
        INDISPONIBILIDADE_REDE_PAT_PORTOVELHO = 391,
        INDISPONIBILIDADE_REDE_PAT_RIOBRANCO = 392,
        INDISPONIBILIDADE_REDE_PAT_SAOLUIS = 393,
        INDISPONIBILIDADE_REDE_PAT_TUCURUI = 394,

		VIAGEM = 330,
		VIAGEM_COORDENADOR = 331,
		VIAGEM_DIRETORIA = 332,
		VIAGEM_FINANCEIRO = 333,
		VIAGEM_SECRETARIA = 334,
		VIAGEM_RESPONSAVEL = 335,

		PROTOCOLO_FATURA = 340,
		CANAL_GESTANTE = 350,
		CARTA_POSITIVA_CRA = 360,
		CARTA_POSITIVA_CRA_APROVAR = 361,

		FORM_EXCLUSAO_CREATE = 365,
		FORM_EXCLUSAO_APROV_NEG = 366,

		RECIPROCIDADE_VIEW = 370,
		RECIPROCIDADE_GESTAO = 371,
		
		RELATORIO_PROVISAO = 201,
		RELATORIO_PAGAMENTO = 202,
		RELATORIO_CONTABILIZACAO_EVIDA_ELN = 203,
		RELATORIO_AUTORIZACAO = 204,
		RELATORIO_FATURAMENTO_USUARIO = 205,
		RELATORIO_MENSALIDADE = 206,
		RELATORIO_RECIPROCIDADE = 207,
		RELATORIO_COPARTICIPACAO = 208,
		RELATORIO_BOLETO_VENCIMENTO = 209,
		RELATORIO_BOLETO_NAO_QUITADOS = 210,
		RELATORIO_BENEFICIARIOS_LOCAL = 211,
		RELATORIO_SERVICO_PRESTADOR = 212,
		RELATORIO_CUSTO_INTERNACAO = 213,
		RELATORIO_FRANQUIAS_GERADAS = 214,
		RELATORIO_PARCELAMENTOS = 215,
		RELATORIO_TRAVAMENTO_ISA = 216,
		RELATORIO_BENEFICIARIOS_CCO = 217,
		RELATORIO_DEBITO_CONGELADO = 218,
		RELATORIO_CREDITO_BENEFICIARIO = 219,
        RELATORIO_BENEFICIARIOS_LISTA = 220,
        RELATORIO_CREDENCIADOS_LISTA = 221,
        RELATORIO_DESPESAS_CEA = 222,
		
		GESTAO_RESPONSAVEL = 401,
		GESTAO_QUITACAO = 402,
		GESTAO_ALT_AUTORIZACAO_ISA = 403,
		GESTAO_DEBITO_ANUAL = 404,
		GESTAO_MEDICAMENTO_REEMBOLSAVEL = 405,
		GESTAO_MEDICAMENTO_REEMBOLSAVEL_EDICAO = 406,
		GESTAO_PRINCIPIO_ATIVO_EDICAO = 407,

		IR_BENEFICIARIO = 501,
		IR_CREDENCIADO = 502,
		IR_CONFIGURACAO = 503,

		VISUALIZAR_REUNIAO = 601,
		GERENCIAR_REUNIAO = 602,

		ADESAO = 701,
		ADESAO_VALIDAR = 702,
		ADESAO_INTEGRAR = 703,
	    ADESAO_VALIDAR_ELETRONORTE = 704,
	    ADESAO_VALIDAR_CEA = 705,
	    ADESAO_VALIDAR_EVIDA = 706,
	    ADESAO_VALIDAR_AMAZONASD = 707,
	    ADESAO_VALIDAR_AMAZONASGT = 708,

		TELEFONIA_RAMAL = 801,
		TELEFONIA_RELATORIO_GERENCIAL = 802,

		EXECUTAR_ROTINAS = 9900
	}

	public enum Perfil {
		ADMINISTRADOR = 1,
		FUNCIONARIO = 2,
		DIRETOR_BENEFICIO = 3,
		COORDENADOR = 4,
		AUTORIZACAO = 5,
		CADASTRO = 6,
		CREDENCIAMENTO = 7,
		FINANCEIRO = 8,
		DIRETOR_ADM_FINANCEIRO = 9,
		DIRETOR_PRESIDENTE = 10,
		RECEPCAO = 11,
		REPRESENTANTE = 12,
		ASSESSORIA = 13,
		AUTORIZACAO_ODONTO = 14,
		CONTAS_MEDICAS = 15,
		SECRETARIA_GERAL = 16,
		CONSELHO = 17
	}
}
